import os
import logging
from datetime import datetime, timedelta
from typing import List, Tuple
import pandas as pd
import numpy as np
from sqlalchemy import text

from src.psx_predictor.db.connection import engine
from src.psx_predictor.models.utils import choose_global_cutoff
from src.psx_predictor.models.ablation_study import (
    mean_absolute_error as mae,
    mean_squared_error as rmse,
    mean_absolute_percentage_error as mape,
)

def directional_accuracy(y_true, y_pred):
    """Calculate directional accuracy as percentage of correct sign predictions.

    Returns a float in the range 0‑100.
    """
    return (np.sign(y_true) == np.sign(y_pred)).mean() * 100

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
if not logger.handlers:
    ch = logging.StreamHandler()
    ch.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(ch)

def _get_all_trading_dates() -> List[datetime]:
    """Return a sorted list of all distinct trading dates from the DB."""
    query = text("SELECT DISTINCT date FROM stock_eod_data ORDER BY date ASC")
    with engine.connect() as conn:
        dates = [row[0] for row in conn.execute(query).fetchall()]
    return [pd.to_datetime(d).date() for d in dates]

def generate_walk_forward_windows(
    start_date: str,
    end_date: str,
    train_window_days: int = 750,
    test_window_days: int = 60,
    step_days: int = 60,
    mode: str = "rolling",
) -> List[Tuple[str, str, str, str]]:
    """Generate walk‑forward windows using real trading days.

    Returns a list of tuples ``(train_start, train_end, test_start, test_end)`` as ISO strings.
    ``mode`` can be ``"rolling"`` (fixed look‑back) or ``"expanding"`` (all history up to train_end).
    """
    all_dates = _get_all_trading_dates()
    start_dt = pd.to_datetime(start_date).date()
    end_dt = pd.to_datetime(end_date).date()
    all_dates = [d for d in all_dates if start_dt <= d <= end_dt]
    if not all_dates:
        logger.warning("No trading dates found in the specified range.")
        return []

    windows: List[Tuple[str, str, str, str]] = []
    
    if train_window_days >= len(all_dates):
        logger.warning(f"Not enough trading days ({len(all_dates)}) to form a training window of {train_window_days} days.")
        return []
        
    date_index = {d: i for i, d in enumerate(all_dates)}
    test_start_idx = train_window_days
    
    while test_start_idx < len(all_dates):
        test_end_idx = min(test_start_idx + test_window_days - 1, len(all_dates) - 1)
        test_start = all_dates[test_start_idx]
        test_end = all_dates[test_end_idx]
        if mode == "expanding":
            train_start = start_dt
        elif mode == "rolling":
            train_start_idx = max(0, test_start_idx - train_window_days)
            train_start = all_dates[train_start_idx]
        else:
            raise ValueError("mode must be 'rolling' or 'expanding'")
        train_end = test_start - timedelta(days=1)
        if train_end < train_start:
            logger.warning("Insufficient training days for current window; stopping generation.")
            break
        windows.append((train_start.isoformat(), train_end.isoformat(), test_start.isoformat(), test_end.isoformat()))
        test_start_idx += step_days
        if len(windows) > 1000:
            logger.error("Too many windows generated; breaking to avoid infinite loop.")
            break
    if len(windows) < 3:
        logger.warning(f"Only {len(windows)} windows generated; attempting to reduce test_window_days.")
        if test_window_days > 30:
            return generate_walk_forward_windows(
                start_date,
                end_date,
                train_window_days,
                test_window_days // 2,
                step_days,
                mode,
            )
        else:
            logger.error("Unable to generate enough windows for walk‑forward validation.")
            return []
    return windows

def run_walk_forward(
    model_factory,
    feature_fn,
    windows: List[Tuple[str, str, str, str]],
    tickers: List[str],
) -> pd.DataFrame:
    """Run walk‑forward evaluation for a given model.

    * ``model_factory`` – callable that returns an *untrained* model instance.
    * ``feature_fn`` – callable ``feature_fn(ticker, start_date, end_date)`` returning ``(X, y, dates, close)``.
    * ``windows`` – list generated by :func:`generate_walk_forward_windows`.
    * ``tickers`` – list of tickers to evaluate.
    Returns a DataFrame with one row per (window, ticker).
    """
    rows = []
    for window_idx, (train_start, train_end, test_start, test_end) in enumerate(windows):
        logger.info(f"Processing window {window_idx + 1}/{len(windows)}: {train_start}–{train_end} (train) | {test_start}–{test_end} (test)")
        for ticker in tickers:
            try:
                X_train, y_train, dates_train, close_train = feature_fn(ticker, train_start, train_end)
                X_test, y_test, dates_test, close_test = feature_fn(ticker, test_start, test_end)
            except Exception as e:
                logger.warning(f"Skipping ticker {ticker} for window due to data error: {e}")
                continue

            if len(X_train) == 0 or len(X_test) == 0:
                continue

            model = model_factory()
            model.fit(X_train, y_train)
            preds = model.predict(X_test)
            # Naïve persistence baseline (next day's return = 0 change)
            naive_preds = np.zeros(len(y_test))
            mae_val = mae(y_test, preds)
            rmse_val = np.sqrt(rmse(y_test, preds))
            mape_val = mape(y_test, preds)
            dir_acc = directional_accuracy(y_test, preds)
            naive_mae = mae(y_test, naive_preds)
            naive_rmse = np.sqrt(rmse(y_test, naive_preds))
            naive_mape = mape(y_test, naive_preds)
            naive_dir_acc = directional_accuracy(y_test, naive_preds)
            rows.append({
                "ticker": ticker,
                "window_idx": window_idx,
                "train_start": train_start,
                "train_end": train_end,
                "test_start": test_start,
                "test_end": test_end,
                "mae": mae_val,
                "rmse": rmse_val,
                "mape": mape_val,
                "directional_accuracy": dir_acc,
                "naive_mae": naive_mae,
                "naive_rmse": naive_rmse,
                "naive_mape": naive_mape,
                "naive_directional_accuracy": naive_dir_acc,
            })
    return pd.DataFrame(rows)
